'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WeatherConditions.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property defaultweathericonset_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_27_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_27_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_29_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_29_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_31_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_31_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_33_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_33_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_45_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_45_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_46_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_46_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_47_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_47_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_alert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_alert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defaultweathericonset_na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultweathericonset_na", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TWClogo_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TWClogo_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
